In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/ConcreteData_cleaned.csv")

In [7]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

There are no categorical variables in this data set so we will go straight to scaling the numerical columns. The first seven columns contain amounts of ingredients for concrete. They all have the same units, kg/m^3, however the scale varies quite a bit between features/ingredients. I'm not sure if it is better to scale each ingredient individually or, since each ingredient is a proportion of the whole mixture, we could normalize each record (row) independently of the others, such that all the component ingredients sum to 1. We will try both approaches. The Age column should not be included in the normalization and will be scaled separately.

In [ ]:
#Separate features and target variable
X = df.drop(columns=["Concrete compressive strength"])
y = df["Concrete compressive strength"]

In [49]:
#Train/test split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8, random_state=10)

# Normalized per row:

In [5]:
transformer = Normalizer(norm='l1')
transformer.fit(X_train.drop(columns=['Age']))
X_train_norm = transformer.transform(X_train.drop(columns=['Age']))

In [18]:
Scaler = MinMaxScaler()
Scaler.fit(X_train[['Age']])
X_train_Age_scaled = Scaler.transform(X_train[['Age']])

In [20]:
X_test_norm = transformer.transform(X_test.drop(columns=['Age']))
X_test_Age_scaled = Scaler.transform(X_test[['Age']])

In [43]:
X_train_normalized = X_train.copy()
X_train_normalized.iloc[:,0:7] = X_train_norm
X_train_normalized['Age'] = X_train_normalized['Age'].astype(float)
X_train_normalized.loc[:,'Age'] = X_train_Age_scaled

In [44]:
X_train_normalized.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
426,0.073556,0.039514,0.067670,0.072934,0.004118,0.426247,0.315961,0.146409
240,0.088756,0.000000,0.052241,0.066567,0.003282,0.454416,0.334737,0.069061
590,0.138004,0.000000,0.000000,0.078132,0.000000,0.451380,0.332484,0.069061
600,0.106293,0.000000,0.000000,0.077381,0.000000,0.467687,0.348639,0.069061
448,0.185709,0.009993,0.032895,0.067455,0.004834,0.402647,0.296468,0.011050

In [45]:
X_test_normalized = X_test.copy()
X_test_normalized.iloc[:,0:7] = X_test_norm
X_test_normalized['Age'] = X_test_normalized['Age'].astype(float)
X_test_normalized.loc[:,'Age'] = X_test_Age_scaled

In [46]:
X_test_normalized.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
923,0.068981,0.000000,0.063634,0.086137,0.004055,0.466735,0.310459,0.069061
222,0.102487,0.000000,0.040517,0.080362,0.003014,0.408961,0.364660,0.267956
973,0.072868,0.000000,0.088799,0.080412,0.005592,0.376897,0.375433,0.069061
250,0.106967,0.000000,0.050328,0.080193,0.002447,0.437623,0.322442,0.069061
445,0.185709,0.009993,0.032895,0.067455,0.004834,0.402647,0.296468,0.069061

In [48]:
X_train_normalized.to_csv("data/X_train_normalized.csv")
X_test_normalized.to_csv("data/X_test_normalized.csv")

# Scaled per column:

In [52]:
Scaler.fit(X_train)
X_train_scale = Scaler.transform(X_train)
X_test_scale = Scaler.transform(X_test)

In [56]:
X_train_scaled = X_train.copy()
X_train_scaled['Age'] = X_train_scaled['Age'].astype(float)
X_train_scaled.loc[:,:] = X_train_scale
X_test_scaled = X_test.copy()
X_test_scaled['Age'] = X_test_scaled['Age'].astype(float)
X_test_scaled.loc[:,:] = X_test_scale

In [59]:
X_train_scaled.to_csv("data/X_train_scaled.csv")
X_test_scaled.to_csv("data/X_test_scaled.csv")